---
name: R-CMD-check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository and initialize Git LFS
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true  # Enable Git LFS
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R/
          key: ${{ runner.os }}-R-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-R-
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          Rscript -e "install.packages('rcmdcheck')"
      - name: Run R CMD check using r-lib
        uses: r-lib/actions/check-r-package@v2
