---
name: R Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository and initialize Git LFS
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS

      # Step 2: Setup R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Step 3: Install R package dependencies
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run R CMD check using r-lib
        uses: r-lib/actions/check-r-package@v2
